apiVersion: v1
kind: Namespace
metadata:
  name: serverlegends
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverlegends-bot
  namespace: serverlegends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serverlegends-bot
  template:
    metadata:
      labels:
        app: serverlegends-bot
    spec:
      containers:
        - name: bot
          image: serverlegends-bot:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: serverlegends-secret
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
